# Solar Transformer

In [ ]:
!pip install wandb tensorflow_probability tensorflow_addons

In [ ]:
from tensorflow.keras.layers import Add, Dense, Dropout, Layer, LayerNormalization, MultiHeadAttention
from tensorflow.keras.models import Model
from tensorflow.keras.initializers import TruncatedNormal
from tensorflow.keras.callbacks import EarlyStopping, LearningRateScheduler, Callback
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.metrics import MeanSquaredError, RootMeanSquaredError, MeanAbsoluteError
from tensorflow_addons.metrics import RSquare
from wandb.keras import WandbCallback

import math
import wandb
import pandas as pd
import tensorflow as tf
import tensorflow_probability as tfp
import tensorflow_addons as tfa
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

## Plotting

In [ ]:
def plot_4d(matrix):
    fig = plt.figure(figsize=(10, 20), dpi=300)
    plt.title("Attention heatmap")

    # create grid
    x = np.arange(0, matrix.shape[0], 1, dtype=np.int32)  # timesteps
    y = np.arange(0, matrix.shape[1], 1, dtype=np.int32)    # patches
    z = np.arange(0, matrix.shape[2], 1, dtype=np.int32)  # timesteps
    X, Y, Z = np.meshgrid(x, y, z)

    X = X.transpose([1, 0, 2])
    Y = Y.transpose([1, 0, 2])
    Z = Z.transpose([1, 0, 2])

    for I in range(matrix.shape[3]):
        # Plot
        ax = plt.subplot(5, 5, I+1, projection="3d")
        ax.scatter3D(X, Y, Z, c=matrix[:, :, :, I], marker='s', s=99, cmap='jet')
        ax.set_title(
            f"{I}-th patch"
        )
        ax.set_xlabel("Timestep")
        ax.set_ylabel("Patch")
        ax.set_zlabel("Timestep")

    plt.show()

In [ ]:
def patch_similarity_plot(pos):
  similarity_scores = np.dot(
      pos, np.transpose(pos)
  ) / (
      np.linalg.norm(pos, axis=-1)
      * np.linalg.norm(pos, axis=-1)
  )

  plt.figure(figsize=(7, 7), dpi=300)
  ax = sns.heatmap(similarity_scores, center=0)
  ax.set_title("Spatial Positional Embedding")
  ax.set_xlabel("Patch")
  ax.set_ylabel("Patch")
  plt.show()

def timestep_similarity_plot(pos):
  similarity_scores = np.dot(
      pos, np.transpose(pos)
  ) / (
      np.linalg.norm(pos, axis=-1)
      * np.linalg.norm(pos, axis=-1)
  )

  plt.figure(figsize=(7, 7), dpi=300)
  ax = sns.heatmap(similarity_scores, center=0)
  ax.set_title("Temporal Positional Embedding")
  ax.set_xlabel("Timestep")
  ax.set_ylabel("Timestep")
  plt.show()

In [ ]:
def plot_prediction(inputs, model, max_subplots=3):
  inputs, targets = inputs
  inputs = inputs[:, :-1]

  plt.figure(figsize=(12, 15))
  max_n = min(max_subplots, len(targets))
  for n in range(max_n):
    # input
    plt.subplot(max_n, 1, n+1)
    plt.ylabel('Solar irradiance [kW-hr/m^2/day]')
    plt.plot(np.arange(targets.shape[1]-1), targets[n, :-1, 0, -1], label='Inputs', marker='.', zorder=-10)

    # real
    plt.scatter(np.arange(1, targets.shape[1]), targets[n, 1:, 0, -1], edgecolors='k', label='Targets', c='#2cb01d', s=64)
    
    # predicted
    predictions = model([inputs, targets[:, :-1]], training=False)
    plt.scatter(np.arange(1, targets.shape[1]), predictions[n, :, 0, -1], marker='X', edgecolors='k', label='Predictions', c='#fe7e0f', s=64)

    if n == 0:
      plt.legend()

  plt.xlabel('Time [day]')
  plt.show()

## Init logger

In [ ]:
wandb.login()

sweep_config = {
  'method': 'grid',
  'metric': {
    'goal': 'minimize',
    'name': 'val_mean_squared_error'
  },
  'parameters': {
      'epochs': {
        'value': 1000
      },
      'num_encoder_layers': {
        'value': 3
      },
      'num_decoder_layers': {
        'value': 6
      },
      'embed_layer_size': {
        'value': 64
      },
      'fc_layer_size': {
        'value': 256
      },
      'num_heads': {
        'value': 8
      },
      'dropout': {
        'value': 0.15
      },
      'attention_dropout': {
        'value': 0.25
      },
      'optimizer': {
        'value': 'adamw'
      },
      'global_clipnorm': {
        'value': 2.0
      },
      'learning_rate': {
        'value': 0.005
      },
      'weight_decay': {
        'value': 0.00001
      },
      'warmup_steps': {
        'value': 70
      },
      'window_size': {
        'value': 7           # every 7 days
      },
      'batch_size': {
        'value': 32
      },
    }
}

sweep_id = wandb.sweep(sweep_config, project="solar-transformer")
!export WANDB_AGENT_MAX_INITIAL_FAILURES=1024

## Layer

In [ ]:
class PositionalEmbedding(Layer):
    def __init__(self, units, dropout_rate, **kwargs):
        super(PositionalEmbedding, self).__init__(**kwargs)

        self.units = units

        self.projection = Dense(units, kernel_initializer=TruncatedNormal(stddev=0.02))
        self.dropout = Dropout(rate=dropout_rate)

    def build(self, input_shape):
        super(PositionalEmbedding, self).build(input_shape)

        print("pos_embbeding: ", input_shape)
        self.temporal_position = self.add_weight(
            name="temporal_position",
            shape=(1, input_shape[1], 1, self.units),
            initializer=TruncatedNormal(stddev=0.02),
            trainable=True,
        )
        self.spatial_position = self.add_weight(
            name="spatial_position",
            shape=(1, 1, input_shape[2], self.units),
            initializer=TruncatedNormal(stddev=0.02),
            trainable=True,
        )

    def call(self, inputs, training):
        x = self.projection(inputs)
        x += self.temporal_position
        x += self.spatial_position

        return self.dropout(x, training=training)

In [ ]:
class Normalization(tf.keras.layers.experimental.preprocessing.PreprocessingLayer):
    """A preprocessing layer which normalizes continuous features.
    This layer will shift and scale inputs into a distribution centered around
    0 with standard deviation 1. It accomplishes this by precomputing the mean
    and variance of the data, and calling `(input - mean) / sqrt(var)` at
    runtime.
    The mean and variance values for the layer must be either supplied on
    construction or learned via `adapt()`. `adapt()` will compute the mean and
    variance of the data and store them as the layer's weights. `adapt()` should
    be called before `fit()`, `evaluate()`, or `predict()`.
    For an overview and full list of preprocessing layers, see the preprocessing
    [guide](https://www.tensorflow.org/guide/keras/preprocessing_layers).
    Args:
        axis: Integer, tuple of integers, or None. The axis or axes that should
          have a separate mean and variance for each index in the shape. For
          example, if shape is `(None, 5)` and `axis=1`, the layer will track 5
          separate mean and variance values for the last axis. If `axis` is set
          to `None`, the layer will normalize all elements in the input by a
          scalar mean and variance. Defaults to -1, where the last axis of the
          input is assumed to be a feature dimension and is normalized per
          index. Note that in the specific case of batched scalar inputs where
          the only axis is the batch axis, the default will normalize each index
          in the batch separately. In this case, consider passing `axis=None`.
        mean: The mean value(s) to use during normalization. The passed value(s)
          will be broadcast to the shape of the kept axes above; if the value(s)
          cannot be broadcast, an error will be raised when this layer's
          `build()` method is called.
        variance: The variance value(s) to use during normalization. The passed
          value(s) will be broadcast to the shape of the kept axes above; if the
          value(s) cannot be broadcast, an error will be raised when this
          layer's `build()` method is called.
        invert: If True, this layer will apply the inverse transformation
          to its inputs: it would turn a normalized input back into its
          original form.
    Examples:
    Calculate a global mean and variance by analyzing the dataset in `adapt()`.
    >>> adapt_data = np.array([1., 2., 3., 4., 5.], dtype='float32')
    >>> input_data = np.array([1., 2., 3.], dtype='float32')
    >>> layer = tf.keras.layers.Normalization(axis=None)
    >>> layer.adapt(adapt_data)
    >>> layer(input_data)
    <tf.Tensor: shape=(3,), dtype=float32, numpy=
    array([-1.4142135, -0.70710677, 0.], dtype=float32)>
    Calculate a mean and variance for each index on the last axis.
    >>> adapt_data = np.array([[0., 7., 4.],
    ...                        [2., 9., 6.],
    ...                        [0., 7., 4.],
    ...                        [2., 9., 6.]], dtype='float32')
    >>> input_data = np.array([[0., 7., 4.]], dtype='float32')
    >>> layer = tf.keras.layers.Normalization(axis=-1)
    >>> layer.adapt(adapt_data)
    >>> layer(input_data)
    <tf.Tensor: shape=(1, 3), dtype=float32, numpy=
    array([-1., -1., -1.], dtype=float32)>
    Pass the mean and variance directly.
    >>> input_data = np.array([[1.], [2.], [3.]], dtype='float32')
    >>> layer = tf.keras.layers.Normalization(mean=3., variance=2.)
    >>> layer(input_data)
    <tf.Tensor: shape=(3, 1), dtype=float32, numpy=
    array([[-1.4142135 ],
           [-0.70710677],
           [ 0.        ]], dtype=float32)>
    Use the layer to de-normalize inputs (after adapting the layer).
    >>> adapt_data = np.array([[0., 7., 4.],
    ...                        [2., 9., 6.],
    ...                        [0., 7., 4.],
    ...                        [2., 9., 6.]], dtype='float32')
    >>> input_data = np.array([[1., 2., 3.]], dtype='float32')
    >>> layer = tf.keras.layers.Normalization(axis=-1, invert=True)
    >>> layer.adapt(adapt_data)
    >>> layer(input_data)
    <tf.Tensor: shape=(1, 3), dtype=float32, numpy=
    array([2., 10., 8.], dtype=float32)>
    """

    def __init__(
        self, axis=-1, mean=None, variance=None, invert=False, **kwargs
    ):
        super().__init__(**kwargs)

        # Standardize `axis` to a tuple.
        if axis is None:
            axis = ()
        elif isinstance(axis, int):
            axis = (axis,)
        else:
            axis = tuple(axis)
        self.axis = axis

        # Set `mean` and `variance` if passed.
        if isinstance(mean, tf.Variable):
            raise ValueError(
                "Normalization does not support passing a Variable "
                "for the `mean` init arg."
            )
        if isinstance(variance, tf.Variable):
            raise ValueError(
                "Normalization does not support passing a Variable "
                "for the `variance` init arg."
            )
        if (mean is not None) != (variance is not None):
            raise ValueError(
                "When setting values directly, both `mean` and `variance` "
                "must be set. Got mean: {} and variance: {}".format(
                    mean, variance
                )
            )
        self.input_mean = mean
        self.input_variance = variance
        self.invert = invert

    def build(self, input_shape):
        super().build(input_shape)

        if isinstance(input_shape, (list, tuple)) and all(
            isinstance(shape, tf.TensorShape) for shape in input_shape
        ):
            raise ValueError(
                "Normalization only accepts a single input. If you are "
                "passing a python list or tuple as a single input, "
                "please convert to a numpy array or `tf.Tensor`."
            )

        input_shape = tf.TensorShape(input_shape).as_list()
        ndim = len(input_shape)

        if any(a < -ndim or a >= ndim for a in self.axis):
            raise ValueError(
                "All `axis` values must be in the range [-ndim, ndim). "
                "Found ndim: `{}`, axis: {}".format(ndim, self.axis)
            )

        # Axes to be kept, replacing negative values with positive equivalents.
        # Sorted to avoid transposing axes.
        self._keep_axis = sorted([d if d >= 0 else d + ndim for d in self.axis])
        # All axes to be kept should have known shape.
        for d in self._keep_axis:
            if input_shape[d] is None:
                raise ValueError(
                    "All `axis` values to be kept must have known shape. "
                    "Got axis: {}, "
                    "input shape: {}, with unknown axis at index: {}".format(
                        self.axis, input_shape, d
                    )
                )
        # Axes to be reduced.
        self._reduce_axis = [d for d in range(ndim) if d not in self._keep_axis]
        # 1 if an axis should be reduced, 0 otherwise.
        self._reduce_axis_mask = [
            0 if d in self._keep_axis else 1 for d in range(ndim)
        ]
        # Broadcast any reduced axes.
        self._broadcast_shape = [
            input_shape[d] if d in self._keep_axis else 1 for d in range(ndim)
        ]
        mean_and_var_shape = tuple(input_shape[d] for d in self._keep_axis)

        if self.input_mean is None:
            self.adapt_mean = self.add_weight(
                name="mean",
                shape=mean_and_var_shape,
                dtype=self.compute_dtype,
                initializer="zeros",
                trainable=False,
            )
            self.adapt_variance = self.add_weight(
                name="variance",
                shape=mean_and_var_shape,
                dtype=self.compute_dtype,
                initializer="ones",
                trainable=False,
            )
            self.count = self.add_weight(
                name="count",
                shape=(),
                dtype=tf.int64,
                initializer="zeros",
                trainable=False,
            )
            self.finalize_state()
        else:
            # In the no adapt case, make constant tensors for mean and variance
            # with proper broadcast shape for use during call.
            mean = self.input_mean * np.ones(mean_and_var_shape)
            variance = self.input_variance * np.ones(mean_and_var_shape)
            mean = tf.reshape(mean, self._broadcast_shape)
            variance = tf.reshape(variance, self._broadcast_shape)
            self.mean = tf.cast(mean, self.compute_dtype)
            self.variance = tf.cast(variance, self.compute_dtype)

    # We override this method solely to generate a docstring.
    def adapt(self, data, batch_size=None, steps=None):
        """Computes the mean and variance of values in a dataset.
        Calling `adapt()` on a `Normalization` layer is an alternative to
        passing in `mean` and `variance` arguments during layer construction. A
        `Normalization` layer should always either be adapted over a dataset or
        passed `mean` and `variance`.
        During `adapt()`, the layer will compute a `mean` and `variance`
        separately for each position in each axis specified by the `axis`
        argument. To calculate a single `mean` and `variance` over the input
        data, simply pass `axis=None`.
        In order to make `Normalization` efficient in any distribution context,
        the computed mean and variance are kept static with respect to any
        compiled `tf.Graph`s that call the layer. As a consequence, if the layer
        is adapted a second time, any models using the layer should be
        re-compiled. For more information see
        `tf.keras.layers.experimental.preprocessing.PreprocessingLayer.adapt`.
        `adapt()` is meant only as a single machine utility to compute layer
        state.  To analyze a dataset that cannot fit on a single machine, see
        [Tensorflow Transform](
        https://www.tensorflow.org/tfx/transform/get_started)
        for a multi-machine, map-reduce solution.
        Arguments:
          data: The data to train on. It can be passed either as a
              `tf.data.Dataset`, or as a numpy array.
          batch_size: Integer or `None`.
              Number of samples per state update.
              If unspecified, `batch_size` will default to 32.
              Do not specify the `batch_size` if your data is in the
              form of datasets, generators, or `keras.utils.Sequence` instances
              (since they generate batches).
          steps: Integer or `None`.
              Total number of steps (batches of samples)
              When training with input tensors such as
              TensorFlow data tensors, the default `None` is equal to
              the number of samples in your dataset divided by
              the batch size, or 1 if that cannot be determined. If x is a
              `tf.data` dataset, and 'steps' is None, the epoch will run until
              the input dataset is exhausted. When passing an infinitely
              repeating dataset, you must specify the `steps` argument. This
              argument is not supported with array inputs.
        """
        super().adapt(data, batch_size=batch_size, steps=steps)

    def update_state(self, data):
        if self.input_mean is not None:
            raise ValueError(
                "Cannot `adapt` a Normalization layer that is initialized with "
                "static `mean` and `variance`, "
                "you passed mean {} and variance {}.".format(
                    self.input_mean, self.input_variance
                )
            )

        if not self.built:
            raise RuntimeError("`build` must be called before `update_state`.")

        data = self._standardize_inputs(data)
        data = tf.cast(data, self.adapt_mean.dtype)
        batch_mean, batch_variance = tf.nn.moments(data, axes=self._reduce_axis)
        batch_shape = tf.shape(data, out_type=self.count.dtype)
        if self._reduce_axis:
            batch_reduce_shape = tf.gather(batch_shape, self._reduce_axis)
            batch_count = tf.reduce_prod(batch_reduce_shape)
        else:
            batch_count = 1

        total_count = batch_count + self.count
        batch_weight = tf.cast(batch_count, dtype=self.compute_dtype) / tf.cast(
            total_count, dtype=self.compute_dtype
        )
        existing_weight = 1.0 - batch_weight

        total_mean = (
            self.adapt_mean * existing_weight + batch_mean * batch_weight
        )
        # The variance is computed using the lack-of-fit sum of squares
        # formula (see
        # https://en.wikipedia.org/wiki/Lack-of-fit_sum_of_squares).
        total_variance = (
            self.adapt_variance + (self.adapt_mean - total_mean) ** 2
        ) * existing_weight + (
            batch_variance + (batch_mean - total_mean) ** 2
        ) * batch_weight
        self.adapt_mean.assign(total_mean)
        self.adapt_variance.assign(total_variance)
        self.count.assign(total_count)

    def reset_state(self):
        if self.input_mean is not None or not self.built:
            return

        self.adapt_mean.assign(tf.zeros_like(self.adapt_mean))
        self.adapt_variance.assign(tf.ones_like(self.adapt_variance))
        self.count.assign(tf.zeros_like(self.count))

    def finalize_state(self):
        if self.input_mean is not None or not self.built:
            return

        # In the adapt case, we make constant tensors for mean and variance with
        # proper broadcast shape and dtype each time `finalize_state` is called.
        self.mean = tf.reshape(self.adapt_mean, self._broadcast_shape)
        self.mean = tf.cast(self.mean, self.compute_dtype)
        self.variance = tf.reshape(self.adapt_variance, self._broadcast_shape)
        self.variance = tf.cast(self.variance, self.compute_dtype)

    def call(self, inputs):
        inputs = self._standardize_inputs(inputs)
        # The base layer automatically casts floating-point inputs, but we
        # explicitly cast here to also allow integer inputs to be passed
        inputs = tf.cast(inputs, self.compute_dtype)
        if self.invert:
            return (inputs + self.mean) * tf.maximum(
                tf.sqrt(self.variance), tf.keras.backend.epsilon()
            )
        else:
            return (inputs - self.mean) / tf.maximum(
                tf.sqrt(self.variance), tf.keras.backend.epsilon()
            )

    def compute_output_shape(self, input_shape):
        return input_shape

    def compute_output_signature(self, input_spec):
        return input_spec

    def get_config(self):
        config = super().get_config()
        config.update(
            {
                "axis": self.axis,
                "mean": tf.keras.layers.experimental.preprocessing.preprocessing_utils.utils.listify_tensors(self.input_mean),
                "variance": tf.keras.layers.experimental.preprocessing.preprocessing_utils.utils.listify_tensors(self.input_variance),
            }
        )
        return config

    def _standardize_inputs(self, inputs):
        inputs = tf.convert_to_tensor(inputs)
        if inputs.dtype != self.compute_dtype:
            inputs = tf.cast(inputs, self.compute_dtype)
        return inputs

In [ ]:
class Encoder(Layer):
    def __init__(
        self, embed_dim, mlp_dim, num_heads, dropout_rate, attention_dropout_rate, **kwargs
    ):
        super(Encoder, self).__init__(**kwargs)

        # Multi-head Attention
        self.mha = MultiHeadAttention(
            num_heads=num_heads,
            key_dim=embed_dim,
            dropout=attention_dropout_rate,
            kernel_initializer=TruncatedNormal(stddev=0.02),
            attention_axes=(1, 2),       # 2D attention (timestep, patch)
        )

        # Point wise feed forward network
        self.dense_0 = Dense(
            units=mlp_dim,
            activation="gelu",
            kernel_initializer=TruncatedNormal(stddev=0.02),
        )
        self.dense_1 = Dense(
            units=embed_dim, kernel_initializer=TruncatedNormal(stddev=0.02)
        )

        self.dropout_0 = Dropout(rate=dropout_rate)
        self.dropout_1 = Dropout(rate=dropout_rate)

        self.norm_0 = LayerNormalization(epsilon=1e-12)
        self.norm_1 = LayerNormalization(epsilon=1e-12)

        self.add_0 = Add()
        self.add_1 = Add()

    def call(self, inputs, training):
        # Attention block
        x = self.norm_0(inputs)
        x = self.mha(
            query=x,
            key=x,
            value=x,
            training=training,
        )
        x = self.dropout_0(x, training=training)
        x = self.add_0([x, inputs])

        # MLP block
        y = self.norm_1(x)
        y = self.dense_0(y)
        y = self.dense_1(y)
        y = self.dropout_1(y, training=training)

        return self.add_1([x, y])

In [ ]:
class Decoder(Layer):
    def __init__(
        self, embed_dim, mlp_dim, num_heads, dropout_rate, attention_dropout_rate, **kwargs
    ):
        super(Decoder, self).__init__(**kwargs)

        # MultiHeadAttention
        self.mha_0 = MultiHeadAttention(
            num_heads=num_heads,
            key_dim=embed_dim,
            dropout=attention_dropout_rate,
            kernel_initializer=TruncatedNormal(stddev=0.02),
            attention_axes=(1, 2),          # 2D attention (timestep, patch)
        )
        self.mha_1 = MultiHeadAttention(
            num_heads=num_heads,
            key_dim=embed_dim,
            dropout=attention_dropout_rate,
            kernel_initializer=TruncatedNormal(stddev=0.02),
            attention_axes=(1, 2),          # 2D attention (timestep, patch)
        )

        # Point wise feed forward network
        self.dense_0 = Dense(
            units=mlp_dim,
            activation="gelu",
            kernel_initializer=TruncatedNormal(stddev=0.02),
        )
        self.dense_1 = Dense(
            units=embed_dim, kernel_initializer=TruncatedNormal(stddev=0.02)
        )

        self.dropout_0 = Dropout(rate=dropout_rate)
        self.dropout_1 = Dropout(rate=dropout_rate)
        self.dropout_2 = Dropout(rate=dropout_rate)

        self.norm_0 = LayerNormalization(epsilon=1e-12)
        self.norm_1 = LayerNormalization(epsilon=1e-12)
        self.norm_2 = LayerNormalization(epsilon=1e-12)

        self.add_0 = Add()
        self.add_1 = Add()
        self.add_2 = Add()

    def call(self, inputs, enc_output, training):
        # Attention block
        x = self.norm_0(inputs)
        x = self.mha_0(
            query=x,
            key=x,
            value=x,
            training=training,
        )
        x = self.dropout_0(x, training=training)
        x = self.add_0([x, inputs])

        # Attention block
        y = self.norm_1(x)
        y = self.mha_1(
            query=y,
            key=enc_output,
            value=enc_output,
            training=training,
        )
        y = self.dropout_1(y, training=training)
        y = self.add_1([x, y])

        # MLP block
        z = self.norm_2(y)
        z = self.dense_0(z)
        z = self.dense_1(z)
        z = self.dropout_2(z, training=training)

        return self.add_2([y, z])

## Model

In [ ]:
class DailyTransformer(Model):
    def __init__(
        self,
        num_encoder_layers,
        num_decoder_layers,
        embed_dim,
        mlp_dim,
        num_heads,
        num_outputs,
        dropout_rate,
        attention_dropout_rate,
        **kwargs
    ):
        super(DailyTransformer, self).__init__(**kwargs)

        # Input (normalization of RAW measurements)
        self.input_norm_enc = Normalization(invert=False)
        self.input_norm_dec1 = Normalization(invert=False)
        self.input_norm_dec2 = Normalization(invert=True)

        # Input
        self.pos_embs_0 = PositionalEmbedding(embed_dim, dropout_rate)
        self.pos_embs_1 = PositionalEmbedding(embed_dim, dropout_rate)

        # Encoder
        self.enc_layers = [
            Encoder(embed_dim, mlp_dim, num_heads, dropout_rate, attention_dropout_rate)
            for _ in range(num_encoder_layers)
        ]
        self.norm_0 = LayerNormalization(epsilon=1e-12)

        # Decoder
        self.dec_layers = [
            Decoder(embed_dim, mlp_dim, num_heads, dropout_rate, attention_dropout_rate)
            for _ in range(num_decoder_layers)
        ]
        self.norm_1 = LayerNormalization(epsilon=1e-12)

        # Output
        self.final_layer = Dense(
            units=num_outputs,
            kernel_initializer=TruncatedNormal(stddev=0.02),
        )

    def call(self, inputs, training):
        inputs, targets = inputs

        # Encoder input
        x_e = self.input_norm_enc(inputs)
        x_e = self.pos_embs_0(x_e, training=training)

        # Encoder
        for layer in self.enc_layers:
            x_e = layer(x_e, training=training)
        x_e = self.norm_0(x_e)

        # Decoder input
        x_d = self.input_norm_dec1(targets)
        x_d = self.pos_embs_1(x_d, training=training)

        # Decoder
        for layer in self.dec_layers:
            x_d = layer(x_d, x_e, training=training)
        x_d = self.norm_1(x_d)

        # Output
        final_output = self.final_layer(x_d)
        final_output = self.input_norm_dec2(final_output)

        return final_output

    def train_step(self, inputs):
        inputs, targets = inputs
        inputs = inputs[:, :-1]
        targets_inputs = targets[:, :-1]
        targets_real = targets[:, 1:, :, -1:]

        with tf.GradientTape() as tape:
            y_pred = self([inputs, targets_inputs], training=True)
            loss = self.compiled_loss(targets_real, y_pred, regularization_losses=self.losses)

        print(y_pred)
        print(targets_real)

        # Compute gradients
        trainable_vars = self.trainable_variables
        gradients = tape.gradient(loss, trainable_vars)

        # Update weights
        self.optimizer.apply_gradients(zip(gradients, trainable_vars))

        # Update metrics (includes the metric that tracks the loss)
        self.compiled_metrics.update_state(targets_real[:, -1], y_pred[:, -1])

        # Return a dict mapping metric names to current value
        return {m.name: m.result() for m in self.metrics}
    
    def test_step(self, inputs):
        inputs, targets = inputs
        inputs = inputs[:, :-1]
        targets_inputs = targets[:, :-1]
        targets_real = targets[:, 1:, :, -1:]

        # Compute predictions
        y_pred = self([inputs, targets_inputs], training=False)

        # Updates the metrics tracking the loss
        self.compiled_loss(targets_real, y_pred, regularization_losses=self.losses)

        # Update the metrics
        self.compiled_metrics.update_state(targets_real[:, -1], y_pred[:, -1])

        # Return a dict mapping metric names to current value
        # Note that it will include the loss (tracked in self.metrics)
        return {m.name: m.result() for m in self.metrics}

## LR scheduler

In [ ]:
def cosine_schedule(base_lr, total_steps, warmup_steps):
    def step_fn(epoch):
        lr = base_lr
        epoch += 1

        progress = (epoch - warmup_steps) / float(total_steps - warmup_steps)
        progress = tf.clip_by_value(progress, 0.0, 1.0)
        
        lr = lr * 0.5 * (1.0 + tf.cos(math.pi * progress))

        if warmup_steps:
            lr = lr * tf.minimum(1.0, epoch / warmup_steps)

        return lr

    return step_fn

In [ ]:
class PrintLR(Callback):
    def on_epoch_end(self, epoch, logs=None):
        wandb.log({"lr": self.model.optimizer.lr.numpy()}, commit=False)

## Daily Dataset

In [ ]:
df_X = pd.read_csv("/content/drive/MyDrive/Solar-Transformer/1984_2022/X_all_daily.csv")
df_y_daily = pd.read_csv("/content/drive/MyDrive/Solar-Transformer/1984_2022/y_all_daily.csv")

In [ ]:
plt.hist2d(df_X['WindDirection1'], df_X['WindSpeed1'], bins=(50, 50))
plt.colorbar()
plt.xlabel('Wind Direction [deg]')
plt.ylabel('Wind Velocity [m/s]')
plt.title("Wind")
plt.show()

plt.hist2d(df_X['WindDirection1'], df_X['WindSpeedMin1'], bins=(50, 50))
plt.colorbar()
plt.xlabel('Wind Direction [deg]')
plt.ylabel('Min Wind Velocity [m/s]')
plt.title("Min Wind")
plt.show()

plt.hist2d(df_X['WindDirection1'], df_X['WindSpeedMax1'], bins=(50, 50))
plt.colorbar()
plt.xlabel('Wind Direction [deg]')
plt.ylabel('Max Wind Velocity [m/s]')
plt.title("Max Wind")
plt.show()

In [ ]:
date_time = pd.to_datetime(df_X.pop('DateTime'), format='%Y-%m-%d')
num_of_patches = df_X['Name'].nunique()

df_X = df_X.drop(
    columns=['Name', 'Latitude', 'Longitude'] +
            [c for c in df_X.columns if c[:9] == 'WindSpeed'] +
            [c for c in df_X.columns if c[:12] == 'WindSpeedMin'] +
            [c for c in df_X.columns if c[:12] == 'WindSpeedMax'] +
            [c for c in df_X.columns if c[:13] == 'WindDirection']
)
df_y_daily = df_y_daily.drop(
    columns=['DateTime', 'Name', 'Latitude', 'Longitude'] +
            [c for c in df_y_daily.columns if c[:9] == 'WindSpeed'] +
            [c for c in df_y_daily.columns if c[:12] == 'WindSpeedMin'] +
            [c for c in df_y_daily.columns if c[:12] == 'WindSpeedMax'] +
            [c for c in df_y_daily.columns if c[:13] == 'WindDirection']
)

In [ ]:
print(df_X.head())
print(df_y_daily.head())

In [ ]:
plt.hist2d(df_X['WindX1'], df_X['WindY1'], bins=(50, 50))
plt.colorbar()
plt.xlabel('Wind X [m/s]')
plt.ylabel('Wind Y [m/s]')
plt.title("Wind vector")
ax = plt.gca()
ax.axis('tight')
plt.show()

plt.hist2d(df_X['WindXMin1'], df_X['WindYMin1'], bins=(50, 50))
plt.colorbar()
plt.xlabel('Min Wind X [m/s]')
plt.ylabel('Min Wind Y [m/s]')
plt.title("Min Wind vector")
ax = plt.gca()
ax.axis('tight')
plt.show()

plt.hist2d(df_X['WindXMax1'], df_X['WindYMax1'], bins=(50, 50))
plt.colorbar()
plt.xlabel('Max Wind X [m/s]')
plt.ylabel('Max Wind Y [m/s]')
plt.title("Max Wind vector")
ax = plt.gca()
ax.axis('tight')
plt.show()

In [ ]:
x_data = date_time[:(5856 + 5840 + 5840 + 5840):num_of_patches]

plt.figure(figsize=(16, 4))
plt.plot(x_data, df_X["Irradiance1"][:(5856 + 5840 + 5840 + 5840):num_of_patches])
plt.ylabel('kW-hr/m^2/day')
plt.xlabel("Date")
plt.title("Solar irradiance")
plt.show()

plt.figure(figsize=(16, 4))
plt.plot(x_data, df_X["Temp1"][:(5856 + 5840 + 5840 + 5840):num_of_patches])
plt.plot(x_data, df_X["TempMin1"][:(5856 + 5840 + 5840 + 5840):num_of_patches])
plt.plot(x_data, df_X["TempMax1"][:(5856 + 5840 + 5840 + 5840):num_of_patches])
plt.ylabel('°C')
plt.xlabel("Date")
plt.title("Temperature")
plt.legend(["Mean", "Min", "Max"])
plt.show()

plt.figure(figsize=(16, 4))
plt.plot(x_data, df_X["Humidity1"][:(5856 + 5840 + 5840 + 5840):num_of_patches])
plt.ylabel('%')
plt.xlabel("Date")
plt.title("Humidity")
plt.show()

plt.figure(figsize=(16, 4))
plt.plot(x_data, df_X["Pressure1"][:(5856 + 5840 + 5840 + 5840):num_of_patches])
plt.ylabel('kPa')
plt.xlabel("Date")
plt.title("Pressure")
plt.show()

plt.figure(figsize=(16, 4))
plt.plot(x_data, df_X["DaySin"][:(5856 + 5840 + 5840 + 5840):num_of_patches])
plt.plot(x_data, df_X["DayCos"][:(5856 + 5840 + 5840 + 5840):num_of_patches])
plt.xlabel("Date")
plt.title("Time of year signal")
plt.show()

## Dataset

In [ ]:
def make_dataset(data, sequence_length, sequence_stride, sampling_rate):
    def make_window(data):
        dataset = tf.data.Dataset.from_tensor_slices(data)
        dataset = dataset.window(sequence_length, shift=sequence_stride, stride=sampling_rate, drop_remainder=True)
        dataset = dataset.flat_map(lambda x: x.batch(sequence_length, drop_remainder=True))        
        return dataset

    data = np.array(data, dtype=np.float32)
    data = np.reshape(data, (-1, num_of_patches, data.shape[-1]))

    # Split the data
    # (80%, 10%, 10%)
    n = data.shape[0]
    n_train = int(n*0.8)
    n_val = int(n*0.9)
    train_data = data[0:n_train]
    val_data = data[n_train:n_val]
    test_data = data[n_val:]

    return (
        (n_train, make_window(train_data)),
        (n_val - n_train, make_window(val_data)),
        make_window(test_data)
    )

def merge_dataset(datasets, batch_size, shuffle):
    dataset = tf.data.Dataset.zip(datasets)
    dataset = dataset.prefetch(tf.data.AUTOTUNE)

    if shuffle:
        # Shuffle locally at each iteration
        dataset = dataset.shuffle(buffer_size=1000)
    dataset = dataset.batch(batch_size)
    
    return dataset

## Training loop

In [ ]:
def training_loop(cfg):
    # load dataset
    (n_train_X, train_X_ds), (n_val_X, val_X_ds), _ = make_dataset(df_X, (cfg.window_size + 1), 1, 1)
    (n_train_y, train_y_daily_ds), (n_val_y, val_y_daily_ds), _ = make_dataset(df_y_daily, (cfg.window_size + 1), 1, 1)
    assert n_train_X == n_train_y
    assert n_val_X == n_val_y

    train_ds = merge_dataset(
        (train_X_ds, train_y_daily_ds),
        cfg.batch_size,
        shuffle=True,
    )
    val_ds = merge_dataset(
        (val_X_ds, val_y_daily_ds),
        cfg.batch_size,
        shuffle=False,
    )

    # Generate new model
    daily_model = DailyTransformer(
      num_encoder_layers=cfg.num_encoder_layers,
      num_decoder_layers=cfg.num_decoder_layers,
      embed_dim=cfg.embed_layer_size,
      mlp_dim=cfg.fc_layer_size,
      num_heads=cfg.num_heads,
      num_outputs=1,
      dropout_rate=cfg.dropout,
      attention_dropout_rate=cfg.attention_dropout,
    )

    # adapt on inputs of training dataset - must be before model.compile !!!
    daily_model.input_norm_enc.adapt(train_X_ds)
    print(daily_model.input_norm_enc.variables)

    # adapt on targets of training dataset - must be before model.compile !!!
    daily_model.input_norm_dec1.adapt(train_y_daily_ds)
    print(daily_model.input_norm_dec1.variables)
    daily_model.input_norm_dec2.adapt(train_y_daily_ds.map(lambda x: x[:, :, -1:]))
    print(daily_model.input_norm_dec2.variables)

    # Select optimizer
    if cfg.optimizer == "adam":
      optim = Adam(
          beta_1=0.9,
          beta_2=0.999,
          epsilon=1e-08,
          global_clipnorm=cfg.global_clipnorm,
      )
    elif cfg.optimizer == "adamw":
      optim = tfa.optimizers.AdamW(
          weight_decay=cfg.weight_decay,
          beta_1=0.9,
          beta_2=0.999,
          epsilon=1e-08,
          global_clipnorm=cfg.global_clipnorm,
          exclude_from_weight_decay=["layer_normalization", "bias", "temporal_position", "spatial_position"],
      )
    else:
      raise ValueError("The used optimizer is not in list of available")

    daily_model.compile(
        optimizer=optim,
        loss="log_cosh",
        metrics=[MeanSquaredError(), RootMeanSquaredError(), MeanAbsoluteError(), RSquare()]   
    )

    # Train model
    daily_model.fit(
        train_ds,
        epochs=cfg.epochs,
        validation_data=val_ds,
        callbacks=[
            LearningRateScheduler(cosine_schedule(base_lr=cfg.learning_rate, total_steps=cfg.epochs, warmup_steps=cfg.warmup_steps)),
            PrintLR(),
            WandbCallback(monitor="val_mean_squared_error", mode='min', save_weights_only=True),
            EarlyStopping(monitor="val_mean_squared_error", mode='min', min_delta=1e-4, patience=10, restore_best_weights=True, verbose=1),
        ],
        verbose=1
    )

    daily_model.summary()

    patch_similarity_plot(daily_model.pos_embs_0.spatial_position[0, 0])
    patch_similarity_plot(daily_model.pos_embs_1.spatial_position[0, 0])
    
    timestep_similarity_plot(daily_model.pos_embs_0.temporal_position[0, :, 0])
    timestep_similarity_plot(daily_model.pos_embs_1.temporal_position[0, :, 0])

    for inputs in val_ds.take(1):
        plot_prediction(inputs, daily_model)

    # Resets all state generated by Keras
    tf.keras.backend.clear_session()

In [ ]:
def run(config=None):
  with wandb.init(config=config):
      config = wandb.config

      # check rules
      if (config.fc_layer_size < config.embed_layer_size):
          return
      elif (config.warmup_steps >= config.epochs):
          return

      training_loop(config)

In [ ]:
wandb.agent(sweep_id, run, count=1024)